services:
  web:
    build: ./client
    ports: 
      - 3000:3000
    develop:
      watch: 
        - action: rebuild
          path: ./client
          ignore: 
            - node_modules/ 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: friendly
      POSTGRES_PASSWORD: password
    ports: 
      - 5432:5432
    volumes:
      - friendly:/data/db
  api:
    build: ./server
    ports: 
      - 6001:6001
    develop:
      watch: 
        - action: rebuild
          path: ./server
          ignore: 
            - node_modules/ 
    
  

volumes:
  friendly:
